# Generated by Django 3.2.6 on 2021-10-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_dt', models.DateTimeField()),
                ('delta', models.FloatField()),
            ],
        ),
    ]
